[package]
name = "kcore"
description = "Core kernel crate for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
backtrace.workspace = true
kaddr_layout.workspace = true
kerrno.workspace = true
kvfs.workspace = true
kfs.workspace = true
khal.workspace = true
klogger.workspace = true
memspace.workspace = true
memspace_file.workspace = true
kpoll.workspace = true
ksync.workspace = true
ktask.workspace = true
bitflags.workspace = true
cfg-if.workspace = true
event-listener.workspace = true
extern-trait.workspace = true
inherit-methods-macro = "0.1.0"
kernel-elf-parser = { workspace = true }
kspin.workspace = true
lazy_static = { workspace = true }
linkme.workspace = true
memaddr.workspace = true
ouroboros = { version = "0.18.5", default-features = false }
percpu = { workspace = true }
slab.workspace = true
ksignal.workspace = true
kthread.workspace = true
osvm.workspace = true
strum = { workspace = true }
xmas-elf = "0.9"
unittest.workspace = true
kbuild_config = { workspace = true }
tee_task_iface = { workspace = true, optional = true }

[target.'cfg(not(any(target_arch = "aarch64", target_arch = "loongarch64")))'.dependencies]
memspace = { workspace = true, features = ["copy"] }

[features]
tee = ["dep:tee_task_iface", "kthread/tee"]
tee_ta_sign = ["tee_task_iface/tee_ta_sign"]
