[package]
name = "devfs"
description = "Device filesystem (devfs) implementation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
input = ["dep:inputdev", "kclass/input"]
serial = ["kclass/char", "dep:console_driver"]
memtrack = ["kalloc/tracking", "dep:gimli"]
dev-log = []
dice = ["dep:dice_driver", "dep:tee_crypto"]
vmm = ["dep:kvmm-api"]

[dependencies]
block.workspace = true
kalloc.workspace = true
kcred.workspace = true
kexec.workspace = true
kerrno.workspace = true
khal.workspace = true
ktime_types.workspace = true
ktime.workspace = true
inherit-methods-macro = "0.1.0"
klogger.workspace = true
knet.workspace = true
kpoll.workspace = true
kspin.workspace = true
ksync.workspace = true
ktask.workspace = true
kprocess.workspace = true
ktty.workspace = true
kvfs.workspace = true
macros.workspace = true

linux-raw-sys = { workspace = true, features = ["ioctl"] }
memaddr.workspace = true
osvm.workspace = true
posix-types.workspace = true
chrono = { version = "0.4.41", default-features = false }
fbdevice.workspace = true
drmdevice.workspace = true
bitmaps = { version = "3.2.1", default-features = false }
zerocopy = { version = "0.8.26", features = ["derive"] }
lazyinit.workspace = true
flatten_objects = "0.2.4"
backtrace.workspace = true
gimli = { version = "*", default-features = false, optional = true }
dice_driver = { workspace = true, optional = true }
inputdev = { workspace = true, optional = true }
klazy.workspace = true
entropy.workspace = true
kvmm-api = { workspace = true, optional = true }
tee_crypto = { workspace = true, features = ["alloc"], optional = true }
kclass.workspace = true
console_driver = { workspace = true, optional = true }
driver_base.workspace = true
kdevice.workspace = true
unittest.workspace = true
