// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 KylinSoft Co., Ltd. <https://www.kylinos.cn/>
// See LICENSES for license details.

// automatically generated by rust-bindgen 0.69.5
#![allow(clippy::upper_case_acronyms)]

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }

    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }

    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }

    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        unsafe { ::core::slice::from_raw_parts(self.as_ptr(), len) }
    }

    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        unsafe { ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len) }
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 31;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __LONG_DOUBLE_USES_FLOAT128: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const __TIMESIZE: u32 = 64;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const __BITS_PER_LONG: u32 = 64;
pub const _IOC_NRBITS: u32 = 8;
pub const _IOC_TYPEBITS: u32 = 8;
pub const _IOC_SIZEBITS: u32 = 14;
pub const _IOC_DIRBITS: u32 = 2;
pub const _IOC_NRMASK: u32 = 255;
pub const _IOC_TYPEMASK: u32 = 255;
pub const _IOC_SIZEMASK: u32 = 16383;
pub const _IOC_DIRMASK: u32 = 3;
pub const _IOC_NRSHIFT: u32 = 0;
pub const _IOC_TYPESHIFT: u32 = 8;
pub const _IOC_SIZESHIFT: u32 = 16;
pub const _IOC_DIRSHIFT: u32 = 30;
pub const _IOC_NONE: u32 = 0;
pub const _IOC_WRITE: u32 = 1;
pub const _IOC_READ: u32 = 2;
pub const IOC_IN: u32 = 1073741824;
pub const IOC_OUT: u32 = 2147483648;
pub const IOC_INOUT: u32 = 3221225472;
pub const IOCSIZE_MASK: u32 = 1073676288;
pub const IOCSIZE_SHIFT: u32 = 16;
pub const APP_SUBCMD_HELP: &[u8; 5] = b"help\0";
pub const APP_SUBCMD_RTMR: &[u8; 5] = b"rtmr\0";
pub const APP_SUBCMD_ATTESTATION: &[u8; 12] = b"attestation\0";
pub const APP_SUBCMD_SEALING: &[u8; 8] = b"sealing\0";
pub const CSV_GUEST_DEV_PATH: &[u8; 15] = b"/dev/csv-guest\0";
pub const DEV_MEM: &[u8; 9] = b"/dev/mem\0";
pub const PAGE_SIZE: u32 = 4096;
pub const HYGON_SM2_UID_SIZE: u32 = 256;
pub const HYGON_ECC_UID_SIZE: u32 = 256;
pub const HYGON_CHIP_KEY_ID_SIZE: u32 = 16;
pub const HYGON_PUBKEY_SIZE: u32 = 404;
pub const HYGON_SIGNATURE_SIZE: u32 = 144;
pub const HYGON_ROOT_CERT_SIZE: u32 = 832;
pub const HYGON_CSV_CERT_SIZE: u32 = 2084;
pub const CSV_HSK_CEK_DEFAULT_DIR: &[u8; 29] = b"/opt/hygon/demo/csv/hsk_cek/\0";
pub const HYGON_HSK_CEK_CERT_FILE: &[u8; 13] = b"hsk_cek.cert\0";
pub const HYGON_KDS_SERVER_SITE: &[u8; 39] = b"https://cert.hygon.cn/hsk_cek?snumber=\0";
pub const CSV_RTMR_VERSION_MAX: u32 = 1;
pub const CSV_RTMR_VERSION_MIN: u32 = 1;
pub const CSV_RTMR_REG_SIZE: u32 = 32;
pub const CSV_RTMR_EXTEND_LEN: u32 = 32;
pub const CSV_RTMR_REG_NUM: u32 = 5;
pub const CSV_RTMR_REG_INDEX_MAX: u32 = 4;
pub const CCEL_TABLE: &[u8; 31] = b"/sys/firmware/acpi/tables/CCEL\0";
pub const CCEL_SIG: &[u8; 5] = b"CCEL\0";
pub const EV_NO_ACTION: u32 = 3;
pub const EVENT_LOG_OUT_FILE: &[u8; 13] = b"eventlog.bin\0";
pub const RTMR_HASH_ALG_SM3_256: u32 = 18;
pub const SM3_HASH_BLOCK_SIZE: u32 = 32;
pub const VM_ID_SIZE: u32 = 16;
pub const VM_VERSION_SIZE: u32 = 16;
pub const REPORT_USER_DATA_SIZE: u32 = 64;
pub const REPORT_MNONCE_SIZE: u32 = 16;
pub const PEK_CERT_SIZE: u32 = 2084;
pub const SN_SIZE: u32 = 64;
pub const SEALING_KEY_SIZE: u32 = 32;
pub const CSV_ATTESTATION_TEE_INFO_SIZE: u32 = 336;
pub const CSV_ATTESTATION_TEE_INFO_SIGN_SIZE: u32 = 180;
pub const CSV_ATTESTATION_REPORT_SIZE: u32 = 2548;
pub const CSV3_ATTESTATION_TEE_INFO_EXT_SIZE: u32 = 1168;
pub const CSV3_ATTESTATION_TEE_INFO_EXT_SIGN_SIZE: u32 = 1024;
pub const CSV3_ATTESTATION_REPORT_EXT_SIZE: u32 = 4096;
pub const CSV_ATTESTATION_REPORT_OUT_FILE: &[u8; 11] = b"report.bin\0";
pub const CSV_ATTESTATION_MAGIC_LEN: u32 = 16;
pub const CSV_ATTESTATION_MAGIC_STRING: &[u8; 16] = b"ATTESTATION_EXT\0";
pub const CSV_ATTESTATION_FLAG_REPORT_EXT_BIT: u32 = 0;
pub const CSV_ATTESTATION_FLAG_REPORT_EXT: u32 = 1;
pub type __u_char = cty::c_uchar;
pub type __u_short = cty::c_ushort;
pub type __u_int = cty::c_uint;
pub type __u_long = cty::c_ulong;
pub type __int8_t = cty::c_schar;
pub type __uint8_t = cty::c_uchar;
pub type __int16_t = cty::c_short;
pub type __uint16_t = cty::c_ushort;
pub type __int32_t = cty::c_int;
pub type __uint32_t = cty::c_uint;
pub type __int64_t = cty::c_long;
pub type __uint64_t = cty::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = cty::c_long;
pub type __u_quad_t = cty::c_ulong;
pub type __intmax_t = cty::c_long;
pub type __uintmax_t = cty::c_ulong;
pub type __dev_t = cty::c_ulong;
pub type __uid_t = cty::c_uint;
pub type __gid_t = cty::c_uint;
pub type __ino_t = cty::c_ulong;
pub type __ino64_t = cty::c_ulong;
pub type __mode_t = cty::c_uint;
pub type __nlink_t = cty::c_ulong;
pub type __off_t = cty::c_long;
pub type __off64_t = cty::c_long;
pub type __pid_t = cty::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [cty::c_int; 2usize],
}
pub type __clock_t = cty::c_long;
pub type __rlim_t = cty::c_ulong;
pub type __rlim64_t = cty::c_ulong;
pub type __id_t = cty::c_uint;
pub type __time_t = cty::c_long;
pub type __useconds_t = cty::c_uint;
pub type __suseconds_t = cty::c_long;
pub type __daddr_t = cty::c_int;
pub type __key_t = cty::c_int;
pub type __clockid_t = cty::c_int;
pub type __timer_t = *mut cty::c_void;
pub type __blksize_t = cty::c_long;
pub type __blkcnt_t = cty::c_long;
pub type __blkcnt64_t = cty::c_long;
pub type __fsblkcnt_t = cty::c_ulong;
pub type __fsblkcnt64_t = cty::c_ulong;
pub type __fsfilcnt_t = cty::c_ulong;
pub type __fsfilcnt64_t = cty::c_ulong;
pub type __fsword_t = cty::c_long;
pub type __ssize_t = cty::c_long;
pub type __syscall_slong_t = cty::c_long;
pub type __syscall_ulong_t = cty::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut cty::c_char;
pub type __intptr_t = cty::c_long;
pub type __socklen_t = cty::c_uint;
pub type __sig_atomic_t = cty::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = cty::c_schar;
pub type int_fast16_t = cty::c_long;
pub type int_fast32_t = cty::c_long;
pub type int_fast64_t = cty::c_long;
pub type uint_fast8_t = cty::c_uchar;
pub type uint_fast16_t = cty::c_ulong;
pub type uint_fast32_t = cty::c_ulong;
pub type uint_fast64_t = cty::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type wchar_t = cty::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: cty::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
pub type __s8 = cty::c_schar;
pub type __u8 = cty::c_uchar;
pub type __s16 = cty::c_short;
pub type __u16 = cty::c_ushort;
pub type __s32 = cty::c_int;
pub type __u32 = cty::c_uint;
pub type __s64 = cty::c_longlong;
pub type __u64 = cty::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [cty::c_ulong; 16usize],
}
pub type __kernel_sighandler_t = ::core::option::Option<unsafe extern "C" fn(arg1: cty::c_int)>;
pub type __kernel_key_t = cty::c_int;
pub type __kernel_mqd_t = cty::c_int;
pub type __kernel_old_uid_t = cty::c_ushort;
pub type __kernel_old_gid_t = cty::c_ushort;
pub type __kernel_old_dev_t = cty::c_ulong;
pub type __kernel_long_t = cty::c_long;
pub type __kernel_ulong_t = cty::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = cty::c_uint;
pub type __kernel_pid_t = cty::c_int;
pub type __kernel_ipc_pid_t = cty::c_int;
pub type __kernel_uid_t = cty::c_uint;
pub type __kernel_gid_t = cty::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = cty::c_int;
pub type __kernel_uid32_t = cty::c_uint;
pub type __kernel_gid32_t = cty::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [cty::c_int; 2usize],
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = cty::c_longlong;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = cty::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = cty::c_int;
pub type __kernel_clockid_t = cty::c_int;
pub type __kernel_caddr_t = *mut cty::c_char;
pub type __kernel_uid16_t = cty::c_ushort;
pub type __kernel_gid16_t = cty::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = cty::c_uint;
unsafe extern "C" {
    pub static mut g_prog_name: *mut cty::c_char;
}
unsafe extern "C" {
    pub fn open_csv_guest() -> cty::c_int;
}
unsafe extern "C" {
    pub fn convert_ascii_str_to_bin(
        buffer: *mut u8,
        buffer_len: cty::c_int,
        str_: *const cty::c_char,
        str_len: cty::c_int,
    ) -> cty::c_int;
}
unsafe extern "C" {
    pub fn gen_random_data(buffer: *mut cty::c_void, len: u32) -> cty::c_int;
}
unsafe extern "C" {
    pub fn dump_bin(buffer: *mut u8, buffer_len: cty::c_int);
}
pub const key_usage_t_KEY_USAGE_TYPE_HRK: key_usage_t = 0;
pub const key_usage_t_KEY_USAGE_TYPE_HSK: key_usage_t = 19;
pub const key_usage_t_KEY_USAGE_TYPE_INVALID: key_usage_t = 4096;
pub const key_usage_t_KEY_USAGE_TYPE_MIN: key_usage_t = 4097;
pub const key_usage_t_KEY_USAGE_TYPE_OCA: key_usage_t = 4097;
pub const key_usage_t_KEY_USAGE_TYPE_PEK: key_usage_t = 4098;
pub const key_usage_t_KEY_USAGE_TYPE_PDH: key_usage_t = 4099;
pub const key_usage_t_KEY_USAGE_TYPE_CEK: key_usage_t = 4100;
pub const key_usage_t_KEY_USAGE_TYPE_MAX: key_usage_t = 4100;
pub type key_usage_t = cty::c_uint;
pub const curve_id_t_CURVE_ID_TYPE_INVALID: curve_id_t = 0;
pub const curve_id_t_CURVE_ID_TYPE_MIN: curve_id_t = 1;
pub const curve_id_t_CURVE_ID_TYPE_P256: curve_id_t = 1;
pub const curve_id_t_CURVE_ID_TYPE_P384: curve_id_t = 2;
pub const curve_id_t_CURVE_ID_TYPE_SM2_256: curve_id_t = 3;
pub const curve_id_t_CURVE_ID_TYPE_MAX: curve_id_t = 3;
pub type curve_id_t = cty::c_uint;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct hygon_pubkey {
    pub curve_id: u32,
    pub qx: [u8; 72usize],
    pub qy: [u8; 72usize],
    pub userid_len: u16,
    pub userid: [u8; 254usize],
}
pub type hygon_pubkey_t = hygon_pubkey;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct hygon_signature {
    pub r: [u8; 72usize],
    pub s: [u8; 72usize],
}
pub type hygon_signature_t = hygon_signature;
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct hygon_root_cert {
    pub version: u32,
    pub key_id: hygon_root_cert__bindgen_ty_1,
    pub certifying_id: hygon_root_cert__bindgen_ty_1,
    pub key_usage: u32,
    pub reserved1: [u8; 24usize],
    pub __bindgen_anon_1: hygon_root_cert__bindgen_ty_2,
    pub reserved2: [u8; 108usize],
    pub __bindgen_anon_2: hygon_root_cert__bindgen_ty_3,
    pub reserved3: [u8; 112usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hygon_root_cert__bindgen_ty_1 {
    pub id: [u8; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union hygon_root_cert__bindgen_ty_2 {
    pub pubkey: [u8; 404usize],
    pub ecc_pubkey: hygon_pubkey_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union hygon_root_cert__bindgen_ty_3 {
    pub signature: [u8; 144usize],
    pub ecc_sig: hygon_signature_t,
}
pub type hygon_root_cert_t = hygon_root_cert;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct hygon_csv_cert {
    pub version: u32,
    pub api_major: u8,
    pub api_minor: u8,
    pub reserved1: u8,
    pub reserved2: u8,
    pub pubkey_usage: u32,
    pub pubkey_algo: u32,
    pub ecc_pubkey: hygon_pubkey_t,
    pub reserved3: [u8; 624usize],
    pub sig1_usage: u32,
    pub sig1_algo: u32,
    pub ecc_sig1: hygon_signature_t,
    pub reserved4: [u8; 368usize],
    pub sig2_usage: u32,
    pub sig2_algo: u32,
    pub ecc_sig2: hygon_signature_t,
    pub reserved5: [u8; 368usize],
}
pub type hygon_csv_cert_t = hygon_csv_cert;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hygon_csv_cert_chain {
    pub pek_cert: hygon_csv_cert_t,
    pub oca_cert: hygon_csv_cert_t,
    pub cek_cert: hygon_csv_cert_t,
}
pub type hygon_csv_cert_chain_t = hygon_csv_cert_chain;
pub type __check_hygon_pubkey_t = [cty::c_char; 1usize];
pub type __check_hygon_signature_t = [cty::c_char; 1usize];
pub type __check_hygon_root_cert_t = [cty::c_char; 1usize];
pub type __check_hygon_csv_cert_t = [cty::c_char; 1usize];
unsafe extern "C" {
    pub fn verify_hsk_cert(cert: *mut hygon_root_cert_t) -> cty::c_int;
}
unsafe extern "C" {
    pub fn verify_cek_cert(
        hsk_cert: *mut hygon_root_cert_t,
        cek_cert: *mut hygon_csv_cert_t,
    ) -> cty::c_int;
}
unsafe extern "C" {
    pub fn verify_pek_cert(
        cek_cert: *mut hygon_csv_cert_t,
        pek_cert: *mut hygon_csv_cert_t,
    ) -> cty::c_int;
}
unsafe extern "C" {
    pub fn verify_hygon_certchain(
        pek_cert: *mut hygon_csv_cert_t,
        chip_id: *const u8,
    ) -> cty::c_int;
}
unsafe extern "C" {
    pub fn verify_hygon_signature(
        data: *const u8,
        data_len: u32,
        pubkey: *mut hygon_pubkey_t,
        sig: *mut hygon_signature_t,
    ) -> cty::c_int;
}
unsafe extern "C" {
    pub fn handle_subcmd_rtmr(argc: cty::c_int, argv: *mut *mut cty::c_char) -> cty::c_int;
}
pub const csv_guest_user_rtmr_subcmd_CSV_GUEST_USER_RTMR_STATUS: csv_guest_user_rtmr_subcmd = 1;
pub const csv_guest_user_rtmr_subcmd_CSV_GUEST_USER_RTMR_START: csv_guest_user_rtmr_subcmd = 2;
pub const csv_guest_user_rtmr_subcmd_CSV_GUEST_USER_RTMR_READ: csv_guest_user_rtmr_subcmd = 3;
pub const csv_guest_user_rtmr_subcmd_CSV_GUEST_USER_RTMR_EXTEND: csv_guest_user_rtmr_subcmd = 4;
pub type csv_guest_user_rtmr_subcmd = cty::c_uint;
#[doc = " struct csv_guest_user_rtmr_status - RTMR_STATUS subcommand parameters\n\n @version: the \
         RTMR version used in the guest. When in state\n \t     RTMR_STATE_INIT, it will be \
         fixed.\n @state: the state of the guest's RTMR."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_guest_user_rtmr_status {
    pub version: __u16,
    pub state: __u8,
}
#[doc = " struct csv_guest_user_rtmr_start - RTMR_START subcommand parameters\n\n @version: the \
         RTMR version requested by the guest."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_guest_user_rtmr_start {
    pub version: __u16,
}
#[doc = " struct csv_guest_user_rtmr_read - RTMR_READ subcommand parameters\n\n @bitmap: the \
         bitmap specified the RTMR registers to read.\n @data: the buffer to store RTMR registers' \
         data returned by the firmware.\n \t  If read more than one RTMR register, user should \
         provide a larger\n \t  buffer."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_guest_user_rtmr_read {
    pub bitmap: __u32,
    pub data: [__u8; 32usize],
}
#[doc = " struct csv_guest_user_rtmr_extend - RTMR_EXTEND subcommand parameters\n\n @index: the \
         index for extending the RTMR register.\n @rsvd: reserved, just for alignment.\n \
         @data_len: the length of the data to be extended.\n @data: the data to be extended to the \
         RTMR register."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_guest_user_rtmr_extend {
    pub index: __u8,
    pub rsvd: __u8,
    pub data_len: __u16,
    pub data: [__u8; 32usize],
}
#[doc = " struct csv_rtmr_req - RTMR request command\n\n @buf: the RTMR subcommand buffer.\n @len: \
         the length of RTMR subcommand.\n @subcmd_id: the identifier of the RTMR subcommand.\n \
         @rsvd: reserved, just for alignment.\n @fw_error_code: the return code that a RTMR \
         subcommand returned by the\n \t\t   firmware."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_rtmr_req {
    pub buf: __u64,
    pub len: __u64,
    pub subcmd_id: __u16,
    pub rsvd: __u16,
    pub fw_error_code: __u32,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct CCEL {
    pub Signature: [cty::c_char; 4usize],
    pub Length: u32,
    pub Revision: u8,
    pub Checksum: u8,
    pub OemId: [cty::c_char; 6usize],
    pub OemTableId: [cty::c_char; 8usize],
    pub OemRevision: u32,
    pub CreatorId: u32,
    pub CreatorRevision: u32,
    pub Version: u32,
    pub LogLen: u64,
    pub LogStart: u64,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct TCG_DIGEST {
    pub digest: [u8; 20usize],
}
#[repr(C, packed)]
pub struct TCG_PCR_EVENT_HDR {
    pub PCRIndex: u32,
    pub EventType: u32,
    pub digest: TCG_DIGEST,
    pub EventSize: u32,
    pub Event: __IncompleteArrayField<u8>,
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct DigestValue {
    pub hashAlg: u16,
    pub digest: [u8; 32usize],
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct TPML_DIGEST_VALUES {
    pub count: u32,
    pub digests: [DigestValue; 1usize],
}
#[repr(C, packed)]
pub struct TCG_PCR_EVENT2 {
    pub PCRIndex: u32,
    pub EventType: u32,
    pub digests: TPML_DIGEST_VALUES,
    pub EventSize: u32,
    pub Event: __IncompleteArrayField<u8>,
}
unsafe extern "C" {
    pub fn handle_subcmd_sealing(argc: cty::c_int, argv: *mut *mut cty::c_char) -> cty::c_int;
}
pub type sm3_hash_block_t = [u8; 32usize];
#[doc = " structures for CSV attestation report.\n\n This is also referenced as legacy \
         attestation. In the legacy attestation, the\n suze if the tee_info in the report is 0x150 \
         (see structure\n csv_attestation_report). The tee_info does not contain rtmr."]
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct csv_attestation_tee_info {
    pub user_pubkey_digest: sm3_hash_block_t,
    pub vm_id: [u8; 16usize],
    pub vm_version: [u8; 16usize],
    pub user_data: [u8; 64usize],
    pub mnonce: [u8; 16usize],
    pub measure: sm3_hash_block_t,
    pub policy: u32,
    pub sig_usage: u32,
    pub sig_algo: u32,
    pub anonce: u32,
    pub __bindgen_anon_1: csv_attestation_tee_info__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union csv_attestation_tee_info__bindgen_ty_1 {
    pub sig1: [u8; 144usize],
    pub ecc_sig1: hygon_signature_t,
}
#[doc = " structures for CSV attestation report.\n\n This is also referenced as legacy \
         attestation. In the legacy attestation, the\n suze if the tee_info in the report is 0x150 \
         (see structure\n csv_attestation_report). The tee_info does not contain rtmr."]
pub type csv_attestation_tee_info_t = csv_attestation_tee_info;
#[doc = " structures for CSV attestation report.\n\n This is also referenced as legacy \
         attestation. In the legacy attestation, the\n suze if the tee_info in the report is 0x150 \
         (see structure\n csv_attestation_report). The tee_info does not contain rtmr."]
pub type csv3_attestation_tee_info_t = csv_attestation_tee_info_t;
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct csv_attestation_report {
    pub tee_info: csv_attestation_tee_info_t,
    pub pek_cert: [u8; 2084usize],
    pub chip_id: [u8; 64usize],
    pub sealing_key: [u8; 32usize],
    pub sm3_hmac: sm3_hash_block_t,
}
pub type csv_attestation_report_t = csv_attestation_report;
pub type csv3_attestation_report_t = csv_attestation_report_t;
#[doc = " the user space input buffer for legacy attestation.\n\n struct \
         csv_guest_user_data_attestation - ATTESTATION command parameters.\n\n\tIn the legacy \
         attestation, the size of tee_info portion of the\n\tattestation report is 0x150. The \
         tee_info does not contain rtmr.\n\n @user_data: user defined data, it's suggest that \
         contains challenge data\n\t       from the relying party.\n @mnonce: user's random nonce, \
         just for anti-replay attack protection.\n @hash: the sm3 hash of the @user_data and \
         @mnonce."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_guest_user_data_attestation {
    pub user_data: [u8; 64usize],
    pub mnonce: [u8; 16usize],
    pub hash: sm3_hash_block_t,
}
#[doc = " the user space input buffer for legacy attestation.\n\n struct \
         csv_guest_user_data_attestation - ATTESTATION command parameters.\n\n\tIn the legacy \
         attestation, the size of tee_info portion of the\n\tattestation report is 0x150. The \
         tee_info does not contain rtmr.\n\n @user_data: user defined data, it's suggest that \
         contains challenge data\n\t       from the relying party.\n @mnonce: user's random nonce, \
         just for anti-replay attack protection.\n @hash: the sm3 hash of the @user_data and \
         @mnonce."]
pub type csv_guest_user_data_attestation_t = csv_guest_user_data_attestation;
#[doc = " structure for CSV3 attestation report that support extensions.\n\n This is also \
         referenced as extended attestation. In the extended attestation,\n the size of the \
         tee_info in the report is 0x490 (see structure\n csv3_attestation_tee_info_ext). The \
         tee_info contains rtmr by default."]
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct csv3_attestation_tee_info_ext {
    pub user_pubkey_digest: sm3_hash_block_t,
    pub vm_id: [u8; 16usize],
    pub vm_version: [u8; 16usize],
    pub user_data: [u8; 64usize],
    pub mnonce: [u8; 16usize],
    pub measure: sm3_hash_block_t,
    pub policy: u32,
    pub sig_usage: u32,
    pub sig_algo: u32,
    pub build: u32,
    pub rtmr_version: u16,
    pub reserved0: [u8; 14usize],
    pub rtmr: [u8; 160usize],
    pub reserved1: [u8; 656usize],
    pub __bindgen_anon_1: csv3_attestation_tee_info_ext__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union csv3_attestation_tee_info_ext__bindgen_ty_1 {
    pub sig1: [u8; 144usize],
    pub ecc_sig1: hygon_signature_t,
}
#[doc = " structure for CSV3 attestation report that support extensions.\n\n This is also \
         referenced as extended attestation. In the extended attestation,\n the size of the \
         tee_info in the report is 0x490 (see structure\n csv3_attestation_tee_info_ext). The \
         tee_info contains rtmr by default."]
pub type csv3_attestation_tee_info_ext_t = csv3_attestation_tee_info_ext;
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct csv3_attestation_report_ext {
    pub tee_info: csv3_attestation_tee_info_ext_t,
    pub pek_cert: [u8; 2084usize],
    pub chip_id: [u8; 64usize],
    pub sealing_key: [u8; 32usize],
    pub sm3_hmac: sm3_hash_block_t,
    pub reserved: [u8; 716usize],
}
pub type csv3_attestation_report_ext_t = csv3_attestation_report_ext;
pub type attestation_magic = [u8; 16usize];
#[doc = " the user space input buffer for extended attestation.\n\n struct \
         csv_guest_user_data_attestation_ext - ATTESTATION command parameters.\n\n\tIn the \
         extended attestation, the size of tee_info portion of the\n\tattestation report is 0x490. \
         The tee_info contains rtmr by default.\n\n\tCurrently, the extended attestation only \
         supported for CSV3 guest.\n\n @user_data: user defined data, it's suggest that contains \
         challenge data\n\t       from the relying party.\n @mnonce: user's random nonce, just for \
         anti-replay attack protection.\n @hash: the sm3 hash of the @user_data and @mnonce.\n \
         @magic: The magic string indicates this is an extended attestation aware\n\t   request. \
         Due to historical reasons, users always provide a buffer\n\t   that is much larger than \
         the size of structure\n\t   csv_guest_user_data_attestation_ext. The magic string will be \
         used to\n\t   determine whether the user space uses the extended attestation aware\n\t   \
         request. If the user space is using such a request, the flags field\n\t   will be used to \
         indicate the format of the attestation report.\n @flags: the bit flags used to indicate \
         how to extend the attestation report."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_guest_user_data_attestation_ext {
    pub user_data: [u8; 64usize],
    pub mnonce: [u8; 16usize],
    pub hash: sm3_hash_block_t,
    pub magic: attestation_magic,
    pub flags: u32,
}
#[doc = " the user space input buffer for extended attestation.\n\n struct \
         csv_guest_user_data_attestation_ext - ATTESTATION command parameters.\n\n\tIn the \
         extended attestation, the size of tee_info portion of the\n\tattestation report is 0x490. \
         The tee_info contains rtmr by default.\n\n\tCurrently, the extended attestation only \
         supported for CSV3 guest.\n\n @user_data: user defined data, it's suggest that contains \
         challenge data\n\t       from the relying party.\n @mnonce: user's random nonce, just for \
         anti-replay attack protection.\n @hash: the sm3 hash of the @user_data and @mnonce.\n \
         @magic: The magic string indicates this is an extended attestation aware\n\t   request. \
         Due to historical reasons, users always provide a buffer\n\t   that is much larger than \
         the size of structure\n\t   csv_guest_user_data_attestation_ext. The magic string will be \
         used to\n\t   determine whether the user space uses the extended attestation aware\n\t   \
         request. If the user space is using such a request, the flags field\n\t   will be used to \
         indicate the format of the attestation report.\n @flags: the bit flags used to indicate \
         how to extend the attestation report."]
pub type csv_guest_user_data_attestation_ext_t = csv_guest_user_data_attestation_ext;
#[doc = " struct csv_report_req - Request struct for CSV_CMD_GET_REPORT IOCTL.\n\n @report_data: \
         Request and response buffer. When a user requests an\n\t\t attestation report, the buffer \
         pointed to by this field is\n\t\t referred to as the request buffer. The data in the \
         request\n\t\t buffer complies with the `attestation_userdata` or\n\t\t \
         `attestation_userdata_ext` structure. When the request is\n\t\t returned, the buffer \
         pointed to by this field is refereed to as\n\t\t the response buffer, the data in the \
         response buffer complies\n\t\t with `csv_attestation_report` or \
         `csv3_attestation_report_ext`\n\t\t structure.\n @len: Length of the user buffer.\n \
         @reserved: Padding the structure to 16 bytes."]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct csv_report_req {
    pub report_address: __u64,
    pub len: __u32,
    pub reserved: __u32,
}
pub type __check_csv_attestation_tee_info_t = [cty::c_char; 1usize];
pub type __check_csv_attestation_report_t = [cty::c_char; 1usize];
pub type __check_csv3_attestation_tee_info_ext_t = [cty::c_char; 1usize];
pub type __check_csv3_attestation_report_ext_t = [cty::c_char; 1usize];
unsafe extern "C" {
    pub fn handle_subcmd_attestation(argc: cty::c_int, argv: *mut *mut cty::c_char) -> cty::c_int;
}
unsafe extern "C" {
    pub fn do_attestation_report(report_out_buffer: *mut u8, out_size: *mut u32) -> cty::c_int;
}
unsafe extern "C" {
    pub fn do_attestation_report_ext(
        flags: u32,
        report_out_buffer: *mut u8,
        out_size: *mut u32,
    ) -> cty::c_int;
}
