[package]
name = "x86_64-uefi-loader"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "UEFI loader that prepares and enters the x86_64 x-kernel image"

[dependencies]
kaddr_layout = { workspace = true }
kernel_elf_loader = { workspace = true }
boot_info = { workspace = true }
kbuild_config = { workspace = true }
x86_boot_common = { workspace = true }
uefi = { version = "0.36.1", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
log = "0.4"
