// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 KylinSoft Co., Ltd. <https://www.kylinos.cn/>
// See LICENSES for license details.

use std::{collections::HashMap, fmt::Write, path::Path};

use crate::{
    config::write_if_changed,
    error::{KconfigError, Result},
    kconfig::{
        SymbolTable,
        ast::{RangeType, RustType, SymbolType},
    },
};

/// ConfigGenerator generates build system configuration files.
///
/// Note: Modules (tristate 'm' values) are treated as 'y' in this implementation
/// as the rust-kbuild project does not currently support loadable modules.
/// This is a deviation from the Linux kernel Kconfig which generates separate
/// _MODULE defines for module options.
pub struct ConfigGenerator;

impl ConfigGenerator {
    pub fn generate_auto_conf(path: impl AsRef<Path>, symbols: &SymbolTable) -> Result<()> {
        let mut content = String::new();

        writeln!(content, "#").unwrap();
        writeln!(content, "# Automatically generated file; DO NOT EDIT.").unwrap();
        writeln!(content, "#").unwrap();

        let mut sorted_symbols = symbols.all_symbols().collect::<Vec<_>>();
        sorted_symbols.sort_by_key(|(name, _)| *name);
        for (name, symbol) in sorted_symbols {
            // Strip CONFIG_ prefix if present
            let clean_name = name.strip_prefix("CONFIG_").unwrap_or(name);

            if let Some(value) = &symbol.value
                && value != "n"
            {
                writeln!(content, "{}={}", clean_name, value).unwrap();
            }
        }

        write_if_changed(path.as_ref(), &content)?;
        Ok(())
    }

    pub fn generate_autoconf_h(path: impl AsRef<Path>, symbols: &SymbolTable) -> Result<()> {
        let mut content = String::new();

        writeln!(content, "/*").unwrap();
        writeln!(content, " * Automatically generated file; DO NOT EDIT.").unwrap();
        writeln!(content, " */").unwrap();
        writeln!(content).unwrap();

        let mut sorted_symbols = symbols.all_symbols().collect::<Vec<_>>();
        sorted_symbols.sort_by_key(|(name, _)| *name);
        for (name, symbol) in sorted_symbols {
            // Strip CONFIG_ prefix if present
            let clean_name = name.strip_prefix("CONFIG_").unwrap_or(name);

            if let Some(value) = &symbol.value {
                match value.as_str() {
                    "y" => {
                        writeln!(content, "#define {} 1", clean_name).unwrap();
                    }
                    "m" => {
                        // Treat modules as 'y' (no module support in rust-kbuild)
                        // This is a simplification compared to Linux Kconfig which would
                        // generate a separate _MODULE define
                        writeln!(content, "#define {} 1", clean_name).unwrap();
                    }
                    "n" => {
                        // Don't define anything for disabled options
                    }
                    _ => {
                        writeln!(content, "#define {} \"{}\"", clean_name, value).unwrap();
                    }
                }
            }
        }

        write_if_changed(path.as_ref(), &content)?;
        Ok(())
    }

    /// Generate `config.rs` with strictly typed Rust constants derived from a
    /// parsed `.config` map and the authoritative Kconfig `SymbolType` map.
    ///
    /// - Bool symbols are emitted as `bool`.
    /// - Tristate symbols are emitted as `&str`.
    /// - Integer types (`u8`...`isize`) use the exact declared Rust primitive.
    /// - `hex` values are emitted as `usize`.
    /// - `string` values are emitted as `&str`.
    /// - `rangetype` values are emitted as typed array slices (`&[T]`, `&[(T, ...)]`, etc.).
    pub fn generate_rust_consts(
        output_dir: impl AsRef<Path>,
        config: &HashMap<String, String>,
        type_map: &HashMap<String, SymbolType>,
    ) -> Result<()> {
        let output_dir = output_dir.as_ref();
        std::fs::create_dir_all(output_dir)?;

        let config_rs_path = output_dir.join("config.rs");

        let mut content = String::new();
        content.push_str("// Auto-generated by xtask xconfig gen-const from .config\n");
        content.push_str("// DO NOT EDIT MANUALLY\n\n");

        // Sort keys for stable output
        let mut sorted_keys: Vec<&String> = config.keys().collect();
        sorted_keys.sort();

        for key in sorted_keys {
            let value = &config[key];

            content.push_str("#[allow(dead_code)]\n");

            // Strip CONFIG_ prefix to look up in type_map
            let clean_key = key.strip_prefix("CONFIG_").unwrap_or(key.as_str());

            // Try to emit using the authoritative SymbolType from Kconfig
            if let Some(symbol_type) = type_map.get(clean_key)
                && Self::emit_typed_const(&mut content, key, value, symbol_type)?
            {
                continue;
            }

            // Fallback: use heuristics when no type information is available
            Self::emit_heuristic_const(&mut content, key, value)?;
        }

        write_if_changed(&config_rs_path, &content)?;

        println!("📝 Generated config.rs at: {}", config_rs_path.display());

        Ok(())
    }

    /// Emit a `pub const` declaration using the authoritative SymbolType from Kconfig.
    /// Returns `true` if the constant was emitted, `false` to fall back to heuristic.
    fn emit_typed_const(
        content: &mut String,
        key: &str,
        value: &str,
        symbol_type: &SymbolType,
    ) -> Result<bool> {
        match symbol_type {
            SymbolType::Bool => {
                let bool_value = match value {
                    "y" => "true",
                    "n" => "false",
                    other => {
                        eprintln!("⚠️  Warning: Invalid bool value for {}: {}", key, other);
                        return Ok(false);
                    }
                };
                content.push_str(&format!("pub const {}: bool = {};\n\n", key, bool_value));
                Ok(true)
            }

            SymbolType::Tristate => {
                content.push_str(&format!("pub const {}: &str = \"{}\";\n\n", key, value));
                Ok(true)
            }

            SymbolType::String => {
                content.push_str(&format!("pub const {}: &str = \"{}\";\n\n", key, value));
                Ok(true)
            }

            SymbolType::Hex => {
                // Hex type -- emit as usize
                content.push_str(&format!("pub const {}: usize = {};\n\n", key, value));
                Ok(true)
            }

            // Specific integer types: use the exact declared Rust type
            st if st.is_integer_type() => {
                let rust_type = Self::symbol_type_primitive_str(st);
                content.push_str(&format!(
                    "pub const {}: {} = {};\n\n",
                    key, rust_type, value
                ));
                Ok(true)
            }

            SymbolType::Range(range_type) => {
                Self::emit_range_const(content, key, value, range_type)?;
                Ok(true)
            }

            _ => Ok(false),
        }
    }

    /// Return the Rust primitive type string for an integer-class SymbolType.
    fn symbol_type_primitive_str(st: &SymbolType) -> &'static str {
        match st {
            SymbolType::U8 => "u8",
            SymbolType::U16 => "u16",
            SymbolType::U32 => "u32",
            SymbolType::U64 => "u64",
            SymbolType::U128 => "u128",
            SymbolType::Usize => "usize",
            SymbolType::I8 => "i8",
            SymbolType::I16 => "i16",
            SymbolType::I32 => "i32",
            SymbolType::I64 => "i64",
            SymbolType::I128 => "i128",
            SymbolType::Isize => "isize",
            _ => "usize",
        }
    }

    /// Return the Rust primitive type string for a RustType annotation.
    fn rust_type_str(rt: &RustType) -> &'static str {
        match rt {
            RustType::U8 => "u8",
            RustType::U16 => "u16",
            RustType::U32 => "u32",
            RustType::U64 => "u64",
            RustType::U128 => "u128",
            RustType::Usize => "usize",
            RustType::I8 => "i8",
            RustType::I16 => "i16",
            RustType::I32 => "i32",
            RustType::I64 => "i64",
            RustType::I128 => "i128",
            RustType::Isize => "isize",
            RustType::Str => "&str",
            RustType::String => "String",
        }
    }

    /// Emit a range (array) constant using the RangeType from Kconfig.
    fn emit_range_const(
        content: &mut String,
        key: &str,
        value: &str,
        range_type: &RangeType,
    ) -> Result<()> {
        if !value.starts_with('[') || !value.ends_with(']') {
            // Unexpected format -- fall back to raw string
            content.push_str(&format!("pub const {}: &str = \"{}\";\n\n", key, value));
            return Ok(());
        }

        let inner = &value[1..value.len() - 1];

        if inner.is_empty() {
            match range_type {
                RangeType::StringArray => {
                    content.push_str(&format!("pub const {}: &[&str] = &[];\n\n", key));
                }
                RangeType::Tuple(types) => {
                    let tuple_type = types
                        .iter()
                        .map(|t| Self::rust_type_str(t))
                        .collect::<Vec<_>>()
                        .join(", ");
                    content.push_str(&format!(
                        "pub const {}: &[({})] = &[];\n\n",
                        key, tuple_type
                    ));
                }
                RangeType::Primitive(t) => {
                    content.push_str(&format!(
                        "pub const {}: &[{}] = &[];\n\n",
                        key,
                        Self::rust_type_str(t)
                    ));
                }
                RangeType::Unknown => {
                    content.push_str(&format!("pub const {}: &[&str] = &[];\n\n", key));
                }
            }
            return Ok(());
        }

        match range_type {
            RangeType::StringArray => {
                let items: Vec<&str> = inner.split(',').map(|s| s.trim()).collect();
                let str_items: Vec<String> = items
                    .iter()
                    .map(|s| format!("\"{}\"", s.trim_matches('"')))
                    .collect();
                content.push_str(&format!(
                    "pub const {}: &[&str] = &[{}];\n\n",
                    key,
                    str_items.join(", ")
                ));
            }

            RangeType::Tuple(types) => {
                let tuple_type = types
                    .iter()
                    .map(|t| Self::rust_type_str(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                match Self::parse_tuple_array(inner) {
                    Ok((_, rust_code)) => {
                        content.push_str(&format!(
                            "pub const {}: &[({})] = &[\n{}\n];\n\n",
                            key, tuple_type, rust_code
                        ));
                    }
                    Err(e) => {
                        eprintln!(
                            "⚠️  Warning: Failed to parse tuple array for {}: {}",
                            key, e
                        );
                        content.push_str(&format!("pub const {}: &str = \"{}\";\n\n", key, value));
                    }
                }
            }

            RangeType::Primitive(t) => {
                let elem_type = Self::rust_type_str(t);
                let items: Vec<&str> = inner.split(',').map(|s| s.trim()).collect();
                content.push_str(&format!(
                    "pub const {}: &[{}] = &[{}];\n\n",
                    key,
                    elem_type,
                    items.join(", ")
                ));
            }

            RangeType::Unknown => {
                Self::emit_heuristic_array(content, key, inner)?;
            }
        }

        Ok(())
    }

    /// Emit a constant using value-based heuristics (fallback when no Kconfig type is known).
    fn emit_heuristic_const(content: &mut String, key: &str, value: &str) -> Result<()> {
        // Check if it's a range value (starts with [ and ends with ])
        if value.starts_with('[') && value.ends_with(']') {
            let inner = &value[1..value.len() - 1];
            if inner.is_empty() {
                content.push_str(&format!("pub const {}: &[&str] = &[];\n\n", key));
                return Ok(());
            }
            Self::emit_heuristic_array(content, key, inner)?;
            return Ok(());
        }

        // Hex value
        if value.starts_with("0x") || value.starts_with("0X") {
            match usize::from_str_radix(&value[2..], 16) {
                Ok(_) => {
                    content.push_str(&format!("pub const {}: usize = {};\n\n", key, value));
                }
                Err(_) => {
                    eprintln!("⚠️  Warning: Invalid hex value for {}: {}", key, value);
                }
            }
            return Ok(());
        }

        // Unsigned integer
        if let Ok(uint_val) = value.parse::<usize>() {
            content.push_str(&format!("pub const {}: usize = {};\n\n", key, uint_val));
            return Ok(());
        }

        // Signed integer
        if let Ok(int_val) = value.parse::<i64>() {
            content.push_str(&format!("pub const {}: i64 = {};\n\n", key, int_val));
            return Ok(());
        }

        // String fallback
        content.push_str(&format!("pub const {}: &str = \"{}\";\n\n", key, value));
        Ok(())
    }

    /// Emit an array constant using heuristics on the inner content (without brackets).
    fn emit_heuristic_array(content: &mut String, key: &str, inner: &str) -> Result<()> {
        // Check if it's a tuple array: look for '(' character
        if inner.contains('(') && inner.contains(')') {
            match Self::parse_tuple_array(inner) {
                Ok((tuple_type, rust_code)) => {
                    content.push_str(&format!(
                        "pub const {}: &[{}] = &[\n{}\n];\n\n",
                        key, tuple_type, rust_code
                    ));
                }
                Err(e) => {
                    eprintln!(
                        "⚠️  Warning: Failed to parse tuple array for {}: {}",
                        key, e
                    );
                    content.push_str(&format!("pub const {}: &str = \"[{}]\";\n\n", key, inner));
                }
            }
            return Ok(());
        }

        let items: Vec<&str> = inner.split(',').map(|s| s.trim()).collect();
        let first_item = items[0];

        if first_item.starts_with("0x") || first_item.starts_with("0X") {
            let mut valid_items: Vec<String> = Vec::new();
            let mut has_invalid = false;
            for s in &items {
                let trimmed = s.trim();
                if trimmed.starts_with("0x") || trimmed.starts_with("0X") {
                    match usize::from_str_radix(&trimmed[2..], 16) {
                        Ok(_) => valid_items.push(trimmed.to_string()),
                        Err(_) => {
                            eprintln!(
                                "⚠️  Warning: Invalid hex value '{}' in array {}",
                                trimmed, key
                            );
                            has_invalid = true;
                        }
                    }
                } else {
                    eprintln!(
                        "⚠️  Warning: Skipping non-hex item '{}' in hex array {}",
                        trimmed, key
                    );
                    has_invalid = true;
                }
            }
            if has_invalid {
                eprintln!(
                    "⚠️  Warning: {} has mixed types - only hex values will be included",
                    key
                );
            }
            content.push_str(&format!(
                "pub const {}: &[usize] = &[{}];\n\n",
                key,
                valid_items.join(", ")
            ));
        } else if first_item.parse::<usize>().is_ok() {
            let mut valid_items: Vec<String> = Vec::new();
            let mut has_invalid = false;
            for s in &items {
                if s.trim().parse::<usize>().is_ok() {
                    valid_items.push(s.trim().to_string());
                } else {
                    eprintln!(
                        "⚠️  Warning: Skipping non-integer item '{}' in integer array {}",
                        s.trim(),
                        key
                    );
                    has_invalid = true;
                }
            }
            if has_invalid {
                eprintln!(
                    "⚠️  Warning: {} has mixed types - only integer values will be included",
                    key
                );
            }
            content.push_str(&format!(
                "pub const {}: &[usize] = &[{}];\n\n",
                key,
                valid_items.join(", ")
            ));
        } else {
            let str_items: Vec<String> = items
                .iter()
                .map(|s| format!("\"{}\"", s.trim().trim_matches('"')))
                .collect();
            content.push_str(&format!(
                "pub const {}: &[&str] = &[{}];\n\n",
                key,
                str_items.join(", ")
            ));
        }

        Ok(())
    }

    /// Parse tuple array and return (tuple_type, rust_code)
    fn parse_tuple_array(inner: &str) -> Result<(String, String)> {
        let tuples = Self::split_tuples(inner)?;

        if tuples.is_empty() {
            return Err(KconfigError::Config("No tuples found".into()));
        }

        let first_tuple = Self::parse_single_tuple(tuples[0])?;
        let expected_arity = first_tuple.len();
        let types = Self::infer_tuple_types(&first_tuple);

        for (idx, tuple_str) in tuples.iter().enumerate() {
            let elements = Self::parse_single_tuple(tuple_str)?;
            if elements.len() != expected_arity {
                return Err(KconfigError::Config(format!(
                    "Tuple {} has {} elements, but expected {} (from first tuple)",
                    idx,
                    elements.len(),
                    expected_arity
                )));
            }
            let tuple_types = Self::infer_tuple_types(&elements);
            for (elem_idx, (expected_type, actual_type)) in
                types.iter().zip(tuple_types.iter()).enumerate()
            {
                if expected_type != actual_type {
                    return Err(KconfigError::Config(format!(
                        "Type mismatch in tuple {} at position {}: expected {}, got {}",
                        idx, elem_idx, expected_type, actual_type
                    )));
                }
            }
        }

        let tuple_type = format!("({})", types.join(", "));

        let mut rust_lines = Vec::new();
        for tuple_str in tuples {
            let elements = Self::parse_single_tuple(tuple_str)?;
            let formatted = Self::format_tuple_elements(&elements, &types)?;
            rust_lines.push(format!("    {}", formatted));
        }

        Ok((tuple_type, rust_lines.join(",\n")))
    }

    fn split_tuples(s: &str) -> Result<Vec<&str>> {
        let mut tuples = Vec::new();
        let mut start = 0;
        let mut depth: usize = 0;
        let mut in_quotes = false;
        let chars: Vec<char> = s.chars().collect();

        for i in 0..chars.len() {
            match chars[i] {
                '"' => {
                    let is_escaped = i > 0 && chars[i - 1] == '\\';
                    if !is_escaped {
                        in_quotes = !in_quotes;
                    }
                }
                '(' if !in_quotes => {
                    if depth == 0 {
                        start = i;
                    }
                    depth += 1;
                }
                ')' if !in_quotes => {
                    if depth == 0 {
                        return Err(KconfigError::Config("Unmatched closing parenthesis".into()));
                    }
                    depth -= 1;
                    if depth == 0 {
                        tuples.push(&s[start..=i]);
                    }
                }
                _ => {}
            }
        }

        if depth != 0 {
            return Err(KconfigError::Config("Unmatched opening parenthesis".into()));
        }

        Ok(tuples)
    }

    fn parse_single_tuple(tuple_str: &str) -> Result<Vec<String>> {
        let tuple_str = tuple_str.trim();
        if !tuple_str.starts_with('(') || !tuple_str.ends_with(')') {
            return Err(KconfigError::Config(format!(
                "Invalid tuple format: {}",
                tuple_str
            )));
        }

        let inner = &tuple_str[1..tuple_str.len() - 1];
        let mut elements = Vec::new();
        let mut current = String::new();
        let mut depth = 0;
        let mut in_quotes = false;

        for ch in inner.chars() {
            match ch {
                '"' => {
                    in_quotes = !in_quotes;
                    current.push(ch);
                }
                ',' if depth == 0 && !in_quotes => {
                    elements.push(current.trim().to_string());
                    current.clear();
                }
                '(' | '[' if !in_quotes => {
                    depth += 1;
                    current.push(ch);
                }
                ')' | ']' if !in_quotes => {
                    depth -= 1;
                    current.push(ch);
                }
                _ => current.push(ch),
            }
        }

        if !current.trim().is_empty() {
            elements.push(current.trim().to_string());
        }

        Ok(elements)
    }

    fn infer_tuple_types(elements: &[String]) -> Vec<String> {
        elements
            .iter()
            .map(|elem| {
                let trimmed = elem.trim();

                if (trimmed.starts_with('"') && trimmed.ends_with('"'))
                    || (trimmed.starts_with('\'') && trimmed.ends_with('\''))
                {
                    return "&str".to_string();
                }

                if trimmed.starts_with("0x") || trimmed.starts_with("0X") {
                    return "usize".to_string();
                }

                if trimmed.starts_with('-') {
                    return "i64".to_string();
                }

                if trimmed.parse::<u64>().is_ok() {
                    return "usize".to_string();
                }

                "&str".to_string()
            })
            .collect()
    }

    fn format_tuple_elements(elements: &[String], types: &[String]) -> Result<String> {
        if elements.len() != types.len() {
            return Err(KconfigError::Config(format!(
                "Element and type count mismatch: {} elements, {} types",
                elements.len(),
                types.len()
            )));
        }

        let formatted: Vec<String> = elements
            .iter()
            .zip(types.iter())
            .map(|(elem, typ)| {
                let trimmed = elem.trim();
                if typ == "&str" {
                    if trimmed.starts_with('"') && trimmed.ends_with('"') {
                        trimmed.to_string()
                    } else {
                        format!("\"{}\"", trimmed)
                    }
                } else {
                    trimmed.to_string()
                }
            })
            .collect();

        Ok(format!("({})", formatted.join(", ")))
    }
}
