[package]
name = "timer-driver"
description = "platform timer drivers for x-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = []
crosvm = []

[dependencies]
khal = { workspace = true }
kplat = { workspace = true }
kbuild_config = { workspace = true }
log = "0.4"
percpu.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
int_ratio = "0.1"
of = { workspace = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
int_ratio = "0.1"
raw-cpuid = "11.5"
x2apic = "0.5"
x86_apic = { workspace = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.14"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
