[package]
name = "kthread"
description = "Process-side thread/runtime surface for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
tee = ["dep:tee_task_iface"]
tee_ta_sign = []

[dependencies]
extern-trait.workspace = true
hashbrown.workspace = true
kcred.workspace = true
kaddr_layout.workspace = true
kerrno.workspace = true
klogger.workspace = true
kpoll.workspace = true
kfutex.workspace = true
kfs.workspace = true
kprocess.workspace = true
krlimit.workspace = true
kresources.workspace = true
ksignal.workspace = true
ksync.workspace = true
ktask.workspace = true
ktimer.workspace = true
ktypes.workspace = true
lazy_static.workspace = true
memspace.workspace = true
slab.workspace = true
tee_task_iface = { workspace = true, optional = true }
unittest.workspace = true
weak-map.workspace = true
