[package]
name = "entry"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "X TeeOS Entry Crate"
license.workspace = true
homepage.workspace = true

[features]
unittest = ["dep:unittest"]
dma-trace = ["kfeat/dma-trace"]

[dependencies]
kvfs.workspace = true
xcov.workspace = true
kfeat.workspace = true
kfs.workspace = true
khal.workspace = true
kcred.workspace = true
klogger.workspace = true
kruntime.workspace = true
ksync.workspace = true
ktask.workspace = true
cfg-if.workspace = true
linkme.workspace = true
kprocess.workspace = true
kthread.workspace = true
kuaccess.workspace = true
ksyscall.workspace = true
kservices.workspace = true
ktty.workspace = true
kexec.workspace = true
memspace.workspace = true
kbuild_config.workspace = true
indoc = "2"
backtrace.workspace = true
unittest = { workspace = true, optional = true }

[package.metadata.vendor-filter]
platforms = ["riscv64gc-unknown-none-elf", "loongarch64-unknown-none-softfloat"]
all-features = true
