[package]
name = "entry"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "X TeeOS Entry Crate"
license.workspace = true
homepage.workspace = true

[features]
unittest = ["dep:unittest", "dep:unittest_support"]
dma-trace = ["kfeat/dma-trace"]

[dependencies]
kvfs.workspace = true
xcover.workspace = true
kfeat.workspace = true
kfs.workspace = true
khal.workspace = true
klogger.workspace = true
kruntime.workspace = true
ktask.workspace = true
cfg-if.workspace = true
linkme.workspace = true
kthread.workspace = true
kuaccess.workspace = true
ksyscall.workspace = true
kbuild_config.workspace = true
kerrno.workspace = true
posix-process.workspace = true
devfs.workspace = true
memfs.workspace = true
procfs.workspace = true
indoc = "2"
backtrace.workspace = true
unittest = { workspace = true, optional = true }
unittest_support = { workspace = true, optional = true }

[target.'cfg(any(target_arch = "aarch64", target_arch = "x86_64"))'.dependencies]
tee_kernel.workspace = true

[package.metadata.vendor-filter]
platforms = ["riscv64gc-unknown-none-elf", "loongarch64-unknown-none-softfloat"]
all-features = true
