[package]
name = "posix-process"
description = "POSIX process syscall implementations"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
tee = ["kthread/tee"]

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
kbuild_config.workspace = true
kerrno.workspace = true
khal.workspace = true
klogger.workspace = true
kprocess.workspace = true
ksignal.workspace = true
ktask.workspace = true
kthread.workspace = true
linux-raw-sys.workspace = true
linux_sysno.workspace = true
osvm.workspace = true
posix-ipc.workspace = true
posix-types.workspace = true
