[workspace]
resolver = "2"
members = ["xconfig", "convert_cov", "crate_rootfs", "extract_cov"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["KylinSoft Co., Ltd. <https://www.kylinos.cn/>"]
homepage = "https://gitee.com/openkylin/x-kernel"
repository = "https://gitee.com/openkylin/x-kernel"

[workspace.dependencies]
lazy_static = { version = "1.5", features = ["spin_no_std"] }
rsext4 = { path = "../fs/filesystems/rsext4", default-features = false }
