[package]
name = "kprocess"
version.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "Process management for X-Kernel"

[features]
tee = ["dep:tee_task_iface"]
tipc = ["dep:tipc_handle"]

[dependencies]
anon_inodefs.workspace = true
kiface.workspace = true
fs_context.workspace = true
kaddr_layout.workspace = true
karch.workspace = true
kcpu_id_map.workspace = true
kcred.workspace = true
kerrno.workspace = true
kfd.workspace = true
khal.workspace = true
ktime_types.workspace = true
klazy.workspace = true
kpoll.workspace = true
kidentity.workspace = true
kresources.workspace = true
ksignal.workspace = true
klogger.workspace = true
kns.workspace = true
kvfs.workspace = true
posix-types.workspace = true
kspin = { workspace = true }
ksync.workspace = true
ktask.workspace = true
ktimer.workspace = true
lazyinit.workspace = true
linked_list_r4l.workspace = true
memaddr.workspace = true
memspace.workspace = true
tee_task_iface = { workspace = true, optional = true }
tipc_handle = { workspace = true, optional = true }
weak-map.workspace = true
unittest.workspace = true

[dev-dependencies]
kspin = { workspace = true, features = ["smp"] }
