[package]
name = "kprocess"
version.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "Process management for X-Kernel"

[dependencies]
kspin = { workspace = true }
lazyinit.workspace = true
weak-map.workspace = true
unittest.workspace = true

[dev-dependencies]
kspin = { workspace = true, features = ["smp"] }
