[package]
name = "kfutex"
description = "Linux-compatible futex primitives for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
khal.workspace = true
ktime_types.workspace = true
kerrno.workspace = true
klazy.workspace = true
kspin.workspace = true
ktask.workspace = true
kuaccess.workspace = true
linux-raw-sys = { workspace = true, default-features = false, features = ["no_std", "general"] }
memspace.workspace = true
unittest.workspace = true
