[package]
name = "kirq"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Generic kernel IRQ core"

[dependencies]
bitflags = { workspace = true }
kiface = { workspace = true }
kpoll = { workspace = true }
kspin = { workspace = true }
log = { workspace = true }
percpu = { workspace = true }
unittest = { workspace = true }
