[package]
name = "rsext4_vfs"
description = "VFS bridge for the rsext4 filesystem library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = []
times = ["dep:khal"]

[dependencies]
iov_iter.workspace = true
kclass = { workspace = true, features = ["block"] }
kerrno.workspace = true
khal = { workspace = true, optional = true }
ksync.workspace = true
kvfs.workspace = true
rsext4.workspace = true
