[package]
name = "posix-fs"
description = "POSIX filesystem syscall implementations"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bitflags.workspace = true
kfd.workspace = true
kfd_objects.workspace = true
devfs.workspace = true
memfs.workspace = true
ktty.workspace = true
kerrno.workspace = true
kfs.workspace = true
khal.workspace = true
kio.workspace = true
klogger.workspace = true
kpoll.workspace = true
kthread.workspace = true
kvfs.workspace = true
linux-raw-sys = { workspace = true, features = ["ioctl", "loop_device"] }
linux_sysno.workspace = true
osvm.workspace = true
posix-types.workspace = true
unittest.workspace = true
