[package]
name = "posix-fs"
description = "POSIX filesystem syscall implementations"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
ebpf = ["dep:bpffs"]

[dependencies]
bitflags.workspace = true
bpffs = { workspace = true, optional = true }
kfd.workspace = true
kfd_objects.workspace = true
memfs.workspace = true
fs_context.workspace = true
kerrno.workspace = true
kcred.workspace = true
khal.workspace = true
iov_iter.workspace = true
kio.workspace = true
klogger.workspace = true
kpoll.workspace = true
kprocess.workspace = true
kvfs.workspace = true
linux-raw-sys = { workspace = true, features = ["ioctl", "loop_device"] }
linux_sysno.workspace = true
osvm.workspace = true
posix-types.workspace = true
unittest.workspace = true
