[package]
name = "posix-credentials"
description = "POSIX credential syscall implementations"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
kthread = { workspace = true }
kcred = { workspace = true }
kerrno = { workspace = true }
klogger = { workspace = true }
ktask = { workspace = true }
posix-types = { workspace = true }
