[package]
name = "kfd_objects"
description = "FD-backed kernel object implementations for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
bitflags.workspace = true
hashbrown.workspace = true
kerrno.workspace = true
kcred.workspace = true
khal.workspace = true
ktime_types.workspace = true
ktime.workspace = true
kio.workspace = true
klogger.workspace = true
kpoll.workspace = true
kvfs.workspace = true
ksignal.workspace = true
kspin.workspace = true
ksync.workspace = true
ktask.workspace = true
kprocess.workspace = true
linux-raw-sys = { workspace = true, features = ["general", "ioctl"] }
posix-types.workspace = true
unittest.workspace = true
zerocopy.workspace = true
