[package]
name = "kfd_objects"
description = "FD-backed kernel object implementations for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
bitflags.workspace = true
hashbrown.workspace = true
kerrno.workspace = true
kfd.workspace = true
khal.workspace = true
kio.workspace = true
klogger.workspace = true
kpoll.workspace = true
ksignal.workspace = true
kspin.workspace = true
ksync.workspace = true
ktask.workspace = true
kthread.workspace = true
linux-raw-sys = { workspace = true, features = ["general", "ioctl"] }
memaddr.workspace = true
osvm.workspace = true
ringbuf = { version = "0.4.8", default-features = false, features = ["alloc"] }
unittest.workspace = true
zerocopy.workspace = true
