[package]
name = "kworkerpool"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Kernel worker-pool scheduling and ktask runtime"

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(unittest)"] }

[dependencies]
kbuild_config = { workspace = true }
kcpu_id_map = { workspace = true }
kpoll = { workspace = true }
kspin = { workspace = true }
ktime_types = { workspace = true }
ktask = { workspace = true }
log = { workspace = true }
unittest = { workspace = true }
