[package]
name = "procfs"
description = "Procfs support crate for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
fs-ng-vfs.workspace = true
indoc = "2"
kalloc.workspace = true
kcore.workspace = true
kfs.workspace = true
khal.workspace = true
kprocess.workspace = true
ktask.workspace = true
unittest.workspace = true

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.14"
