[package]
name = "kext4"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Checked ext4 storage core for X-Kernel"
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories = ["filesystem", "no-std"]

[features]
default = []
times = ["dep:ktime"]

[dependencies]
bitflags.workspace = true
block = { workspace = true }
iov_iter.workspace = true
kcred.workspace = true
kerrno.workspace = true
klogger.workspace = true
macros.workspace = true
ksync.workspace = true
kvfs.workspace = true
ktime = { workspace = true, optional = true }
ktime_types = { workspace = true }
unittest = { workspace = true }

[target.'cfg(target_os = "none")'.dependencies]
ktask = { workspace = true }

[dev-dependencies]
kalloc = { workspace = true }


[package.metadata.cargo-shear]
# kalloc is indirectly used in tests, so ignore the unused dependency warning
ignored = ["kalloc"]
