[package]
name = "tee_kernel"
description = "TEE support crate extracted from kapi for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = ["linux_sysno/tee", "kalloc/tee", "tee_ss_smx"]
tee_cfg_memtag = []
tee_ss_smx = []
unittest_helpers = ["dep:unittest_support"]
csv_huk_key = ["dep:kcpu"]
# dice_huk_key and virtcca_huk_key are mutually exclusive (compile_error in tee/arch/aarch64/mod.rs).
dice_huk_key = ["dep:dice_driver", "dep:rust-dice"]
virtcca_huk_key = []

[dependencies]
kalloc.workspace = true
unittest.workspace = true
unittest_support = { workspace = true, optional = true }
rust-dice = { workspace = true, optional = true }
mbedtls = { workspace = true }
mbedtls-sys-auto = { workspace = true }
klazy.workspace = true
kcpu = { workspace = true, optional = true }
dice_driver = { workspace = true, optional = true }
kerrno.workspace = true
kvfs.workspace = true
kfs.workspace = true
khal.workspace = true
kio.workspace = true
klogger.workspace = true
knet.workspace = true
ksync.workspace = true
ktask.workspace = true
bitflags.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
cfg-if.workspace = true
lazy_static = { workspace = true }
linux-raw-sys = { workspace = true, features = ["ioctl", "loop_device"] }
osvm.workspace = true
kthread = { workspace = true, features = ["tee"] }
linux_sysno.workspace = true
zerocopy = { version = "0.8.26", features = ["derive"] }
bincode = { version = "2.0.1", default-features = false, features = ["alloc", "derive"] }
tee_raw_sys = { workspace = true }
tee_task_iface = { workspace = true }
uuid = { version = "0.8", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
cty = "0.2"
kbuild_config.workspace = true
subtle = { version = "2", default-features = false }
static_assertions = "1.1.0"
memoffset = { version = "0.9", default-features = false }
flatten_objects = "0.2.4"
rand_chacha = { version = "0.3", default-features = false }
slab = { workspace = true }
rand = { version = "0.9.1", default-features = false, features = [
    "alloc",
    "small_rng",
] }

# [dev-dependencies]
# kapi = { path = "../../api/kapi" }
