[package]
name = "fbdevice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
display.workspace = true
kalloc.workspace = true
kclass = { workspace = true, features = ["display"] }
khal.workspace = true
kspin.workspace = true
lazyinit.workspace = true
log.workspace = true
memaddr.workspace = true
