[package]
name = "watchdog"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Watchdog timer with NMI support for embedded systems"
keywords = ["watchdog", "nmi", "embedded", "no_std"]
categories = ["no-std", "embedded", "hardware-support"]

[features]
default = []
nmi = ["khal/nmi"]

[dependencies]
khal.workspace = true
ktask = { workspace = true, features = ["watchdog"] }
cfg-if.workspace = true
log.workspace = true
percpu.workspace = true
kbuild_config = { workspace = true }
