[package]
name = "kservices"
description = "Kernel services crate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
input = ["dep:inputdev"]
memtrack = ["kalloc/tracking", "dep:gimli"]
vsock = ["knet/vsock"]
dev-log = []
dice = [
	"kalloc/dice",
	"dep:rand_chacha",
	"dep:rust-dice",
	"dep:mbedtls",
]
tee = [
	"dep:tee_kernel",
]

[dependencies]
kalloc.workspace = true
backtrace.workspace = true
unittest = { workspace = true }
unittest_support.workspace = true
rust-dice = { workspace = true, optional = true }
mbedtls = { workspace = true, optional = true }
fbdevice.workspace = true
kdriver.workspace = true
ktypes.workspace = true
kerrno.workspace = true
fs-ng-vfs.workspace = true
kfs.workspace = true
khal.workspace = true
karch.workspace = true
inputdev = { workspace = true, optional = true }
kio.workspace = true
klogger.workspace = true
knet.workspace = true
kpoll.workspace = true
ksync.workspace = true
ktask.workspace = true
bitflags.workspace = true
bitmaps = { version = "3.2.1", default-features = false }
bytemuck.workspace = true
lazyinit.workspace = true
chrono = { version = "0.4.41", default-features = false }
downcast-rs = { version = "2.0", default-features = false, features = ["sync"] }
flatten_objects = "0.2.4"
gimli = { version = "*", default-features = false, optional = true }
hashbrown = { workspace = true }
kspin.workspace = true
lazy_static = { workspace = true }
linkme.workspace = true
linux-raw-sys = { workspace = true, features = ["ioctl", "loop_device"] }
memaddr.workspace = true
of.workspace = true
rand = { version = "0.9.1", default-features = false, features = [
	"alloc",
	"small_rng",
] }
rand_chacha = { version = "0.3", default-features = false, optional = true }
ringbuf = { version = "0.4.8", default-features = false, features = ["alloc"] }
scope-local.workspace = true
slab.workspace = true
kprocess.workspace = true
ksignal.workspace = true
osvm.workspace = true
zerocopy = { version = "0.8.26", features = ["derive"] }
tee_kernel = { workspace = true, optional = true }
kcore.workspace = true
procfs.workspace = true
