[package]
name = "kservices"
description = "Kernel services crate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
input = ["devfs/input"]
memtrack = ["kalloc/tracking", "devfs/memtrack"]
vsock = ["knet/vsock"]
dev-log = ["devfs/dev-log"]
dice = [
	"kalloc/dice",
	"dep:mbedtls",
	"tee_kernel/dice_huk_key",
	"devfs/dice",
]
tee = [
	"dep:tee_kernel",
	"kthread/tee",
	"procfs/tee",
]

[dependencies]
kalloc.workspace = true
backtrace.workspace = true
unittest = { workspace = true }
unittest_support.workspace = true
mbedtls = { workspace = true, optional = true }
kfd.workspace = true
kerrno.workspace = true
kbuild_config.workspace = true
kvfs.workspace = true
kfs.workspace = true
khal.workspace = true
kcred.workspace = true
karch.workspace = true
kio.workspace = true
klogger.workspace = true
knet.workspace = true
kpoll.workspace = true
ksync.workspace = true
ktask.workspace = true
bitflags.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
gimli = { version = "*", default-features = false, optional = true }
kspin.workspace = true
lazy_static = { workspace = true }
linkme.workspace = true
linux-raw-sys = { workspace = true, features = ["ioctl", "loop_device"] }
memaddr.workspace = true
ringbuf = { version = "0.4.8", default-features = false, features = ["alloc"] }
kprocess.workspace = true
kthread.workspace = true
ksignal.workspace = true
osvm.workspace = true
tee_kernel = { workspace = true, optional = true }
kcore.workspace = true
posix-ipc.workspace = true
procfs.workspace = true
devfs.workspace = true
memfs.workspace = true
ktty.workspace = true
