[package]
name = "kvmm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Architecture-independent virtual machine monitor for x-kernel"

[features]
default = []

[dependencies]
log.workspace = true
kaddr_layout.workspace = true
ktask.workspace = true
kalloc.workspace = true
kcpu_id_map.workspace = true
kbuild_config.workspace = true
kspin.workspace = true
ksync.workspace = true
khal.workspace = true
kirq.workspace = true
ktime_types.workspace = true
fs_context.workspace = true
kcred.workspace = true
kvfs.workspace = true
linux-raw-sys.workspace = true
memspace.workspace = true
memaddr.workspace = true
vdev-core.workspace = true
vdev-test-mmio.workspace = true
vdev-virtio-net.workspace = true
vdev-vpl011.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
percpu.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
percpu.workspace = true
