[package]
name = "ksyscall"
description = "Kernel syscall crate for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
vsock = ["posix-net/vsock"]
tee = [
    "dep:tee_kernel",
    "dep:tee_task_iface",
    "kthread/tee",
    "posix-process/tee",
]
tee_ta_sign = ["tee_task_iface?/tee_ta_sign"]
ebpf = ["dep:posix-bpf", "posix-bpf/ebpf", "posix-fs/ebpf"]

[dependencies]
kaddr_layout.workspace = true
kfd.workspace = true
kfd_objects.workspace = true
kfutex.workspace = true
kbuild_config = { workspace = true }
kcred.workspace = true
kerrno.workspace = true
khal.workspace = true
klogger.workspace = true
kpoll.workspace = true
ktask.workspace = true
ktimer.workspace = true
bitflags.workspace = true
kspin.workspace = true
linux-raw-sys = { workspace = true, features = ["ioctl", "loop_device"] }
kprocess.workspace = true
kthread.workspace = true
ksignal.workspace = true
ksync.workspace = true
osvm.workspace = true
linux_sysno.workspace = true
tee_kernel = { workspace = true, optional = true }
tee_task_iface = { workspace = true, optional = true }
kexec.workspace = true
kuaccess.workspace = true
ktty.workspace = true
posix-fs.workspace = true
posix-bpf = { workspace = true, optional = true }
posix-ipc.workspace = true
posix-mm.workspace = true
posix-net.workspace = true
posix-process.workspace = true
posix-types.workspace = true
num_enum = { version = "0.7", default-features = false }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.14"
