[package]
name = "posix-time"
description = "POSIX time syscall implementations"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
kerrno = { workspace = true }
khal = { workspace = true }
klogger = { workspace = true }
kthread = { workspace = true }
linux-raw-sys = { workspace = true }
posix-types = { workspace = true }
