[package]
name = "kworkqueue"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Kernel workqueue semantic core"

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(unittest)"] }

[dependencies]
kcpu_id_map = { workspace = true }
kspin = { workspace = true }
unittest = { workspace = true }
