[package]
name = "acpi"
description = "ACPI table access helpers."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kaddr_layout = { workspace = true }
kernel_boot = { workspace = true }
lazyinit.workspace = true
