[package]
name = "device-res"
edition.workspace = true
description = "OS-agnostic device resource model and provider abstraction"
documentation = "https://kylin-x-kernel.github.io/device_res"
keywords = ["driver", "resource", "x-kernel"]
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
name = "device_res"

[dependencies]
kspin = { workspace = true }
smallvec = { version = "1.15", features = ["const_generics", "union"] }
