[package]
name = "kalloc"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[features]
tee = []
dice = []
default = []
tlsf = []
slab = []
buddy = []
pcp = []
tracking = ["dep:backtrace"]

[dependencies]
alloc-engine = { workspace = true, features = ["buddy-page"] }
backtrace = { workspace = true, optional = true }
cfg-if.workspace = true
kaddr_layout.workspace = true
kerrno.workspace = true
kspin.workspace = true
log.workspace = true
memaddr.workspace = true
percpu.workspace = true
strum = { workspace = true }
unittest.workspace = true
