[package]
name = "khal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Hardware abstraction layer, provides unified APIs for platform-specific operations"

[features]
default = []
smp = ["kplat/smp",]
fp-simd = ["kcpu/fp-simd",]
rtc = []
nmi = ["kplat/nmi"]
pmu = []
tls = ["kcpu/tls"]

ipi = []
irq = []

[dependencies]
kalloc = { workspace = true }
boot_info = { workspace = true }
firmware_handoff = { workspace = true }
kcpu = { workspace = true }
kplat.workspace = true
kbuild_config.workspace = true
kernel_boot.workspace = true
cfg-if.workspace = true
heapless = "0.9"
kspin.workspace = true
lazyinit.workspace = true
linkme = { version = "0.3.33" }
log.workspace = true
memaddr.workspace = true
kaddr_layout.workspace = true
page_table = { workspace = true }
percpu.workspace = true
crate_interface.workspace = true
acpi = { workspace = true }
of = { workspace = true }
unittest.workspace = true
bitflags = { workspace = true }
handler_table = "0.1.2"


[target.'cfg(target_arch = "x86_64")'.dependencies]
multiboot2 = "0.24"

[build-dependencies]
kbuild_config.workspace = true
