[package]
name = "khal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Hardware abstraction layer, provides unified APIs for platform-specific operations"

[package.metadata.cargo-shear]
ignored = ["linkme"]
ignored-paths = ["src/dummy.rs"]

[features]
default = []
smp = ["kplat/smp",]
fp-simd = ["kcpu/fp-simd",]
vmm = ["kernel_boot/vmm", "kcpu/vmm"]
nmi = ["kplat/nmi", "kspin/pmr", "kcpu/pmr"]
pmu = ["kplat/pmu"]
tls = ["kcpu/tls"]

irq = []

[dependencies]
kalloc = { workspace = true }
boot_info = { workspace = true }
firmware_handoff = { workspace = true }
kcpu = { workspace = true }
kirq = { workspace = true }
kplat.workspace = true
kernel_boot.workspace = true
cfg-if.workspace = true
heapless = "0.9"
kspin.workspace = true
ktime_types.workspace = true
lazyinit.workspace = true
linkme.workspace = true
log.workspace = true
memaddr.workspace = true
kaddr_layout.workspace = true
page_table = { workspace = true }
percpu.workspace = true
kiface.workspace = true
acpi = { workspace = true }
of = { workspace = true }
unittest.workspace = true
bitflags = { workspace = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
multiboot2 = "0.24"
