[package]
name = "kvfs"
description = "Virtual filesystem layer for x-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kcred = { workspace = true }
kerrno = { workspace = true}
khal.workspace = true
kpoll = { workspace = true }
ksignal.workspace = true
klazy = { workspace = true }
bitflags = "2.10"
hashbrown = "0.15"
inherit-methods-macro = "0.1"
iov_iter = { workspace = true }
log = "0.4"
linux-raw-sys = { workspace = true, features = ["general", "ioctl"] }
osvm.workspace = true
smallvec = "1.15"
slab.workspace = true
unittest = { workspace = true}
ksync = { workspace = true }
ktask.workspace = true
memaddr = { workspace = true }
pagecache = { workspace = true }
vmobj = { workspace = true }
