[package]
name = "posix-types"
description = "POSIX/Linux ABI type conversions"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
kerrno = { workspace = true }
khal = { workspace = true }
kio = { workspace = true }
linux-raw-sys = { workspace = true }
osvm = { workspace = true }
strum = { workspace = true }
unittest = { workspace = true}
