[package]
name = "procfs"
description = "Procfs support crate for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
sysrq = ["ktask/snapshot"]
tee = ["kthread/tee", "dep:tee_task_iface"]
lock_stat = ["dep:klockstat", "klockstat/stats"]

[dependencies]
kbuild_config.workspace = true
kvfs.workspace = true
kaddr_layout.workspace = true
kalloc.workspace = true
kcpu_id_map.workspace = true
kdevice.workspace = true
khal.workspace = true
klockstat = { workspace = true, optional = true }
kvfs-simple.workspace = true
kprocess.workspace = true
kpoll.workspace = true
kthread.workspace = true
ktask.workspace = true
ktracing.workspace = true
memaddr.workspace = true
memspace.workspace = true
unittest.workspace = true
tee_task_iface = { workspace = true, optional = true }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.14"
