// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 KylinSoft Co., Ltd. <https://www.kylinos.cn/>
// See LICENSES for license details.

//! Compact kernel symbol table (kallsyms-style).
//!
//! A small, allocation-free symbol table is embedded into the kernel image
//! (KFEAT_SYMTAB) so raw backtrace addresses can be annotated with
//! `func+0xoff/0xsize` right at the fault site. Full file/line resolution
//! still happens on the host against `kernel.debug.elf`.
//!
//! The blob lives in `.rodata` as a plain `static` (no dedicated linker
//! section). This keeps the symbol bootstrap convergent: the table only
//! contains `.text` symbols, and `.text` precedes `.rodata` in the linker
//! script, so growing the blob between the first and second link never
//! shifts the addresses stored in the table.
//!
//! ## Blob layout (generated by `xkmake symtab` at build time)
//!
//! ```text
//! header (16 bytes):  magic u32 | count u32 | addr_high u32 | name_blob_len u32
//! entries[count]:     addr_lo u32 | size u32 | name_off u32   (12 bytes each)
//! name blob:          NUL-terminated names, offsets relative to blob start
//! ```
//!
//! `addr_high` is the shared upper 32 bits of every symbol address
//! (e.g. `0xffff8000_00000000`); `addr_lo` is the lower 32 bits. Entries are
//! sorted by `addr_lo` so lookups use binary search.
//!
//! All fields are read with explicit little-endian byte decoding, never via
//! struct casts: the blob is embedded as a 1-byte-aligned byte array, and
//! alignment-sensitive casts would be undefined behavior on targets with
//! strict alignment (e.g. riscv).

use core::fmt;

use klazy::Once;

/// The symbol table blob is generated by `xkmake` into
/// `$TARGET_DIR/kbuild/ksymtab.bin` (empty for direct builds without
/// `xkmake`). It is embedded into the kernel image as a plain `.rodata`
/// static; see the module docs for why this keeps the symbol bootstrap
/// convergent.
const KSYMTAB_LEN: usize = include_bytes!(concat!(env!("OUT_DIR"), "/ksymtab.bin")).len();

static KSYMTAB_BLOB: [u8; KSYMTAB_LEN] = *include_bytes!(concat!(env!("OUT_DIR"), "/ksymtab.bin"));

const SYMTAB_MAGIC: u32 = 0x584b_5354; // "XKST"

const HEADER_SIZE: usize = 16;
const ENTRY_SIZE: usize = 12;

/// A resolved symbol table entry.
#[derive(Clone, Copy)]
struct SymbolRef<'a> {
    /// Function name bytes (without the trailing NUL).
    name: &'a [u8],
    /// Offset of the instruction pointer within the symbol.
    offset: usize,
    /// Function size in bytes (0 when unknown).
    size: usize,
}

/// Compact kernel symbol table parsed from the embedded blob.
struct KernelSymtab<'a> {
    /// Raw entry region (`count * ENTRY_SIZE` bytes).
    entries: &'a [u8],
    /// Number of entries in `entries`.
    count: usize,
    /// NUL-terminated name blob.
    names: &'a [u8],
    /// Shared upper 32 bits of every symbol address.
    addr_high: usize,
}

impl<'a> KernelSymtab<'a> {
    /// Parse a symbol table blob.
    ///
    /// Returns `None` when the blob does not carry the expected magic or is
    /// truncated (e.g. the image was built without KFEAT_SYMTAB).
    fn parse(bytes: &'a [u8]) -> Option<Self> {
        if bytes.len() < HEADER_SIZE {
            return None;
        }
        let magic = u32::from_le_bytes(bytes[0..4].try_into().ok()?);
        if magic != SYMTAB_MAGIC {
            return None;
        }
        let count = u32::from_le_bytes(bytes[4..8].try_into().ok()?) as usize;
        let addr_high = u32::from_le_bytes(bytes[8..12].try_into().ok()?);
        let name_blob_len = u32::from_le_bytes(bytes[12..16].try_into().ok()?) as usize;

        let entries_len = count.checked_mul(ENTRY_SIZE)?;
        let names_start = HEADER_SIZE.checked_add(entries_len)?;
        let names_end = names_start.checked_add(name_blob_len)?;
        if names_end > bytes.len() {
            return None;
        }
        Some(Self {
            entries: &bytes[HEADER_SIZE..names_start],
            count,
            names: &bytes[names_start..names_end],
            // On 32-bit targets the upper word is truncated away; lookups
            // then simply cannot match kernel addresses, which is safe.
            addr_high: ((u64::from(addr_high)) << 32) as usize,
        })
    }

    /// Read entry `index` with explicit little-endian decoding.
    fn entry(&self, index: usize) -> Option<(u32, u32, u32)> {
        let start = index.checked_mul(ENTRY_SIZE)?;
        let bytes = self.entries.get(start..start.checked_add(ENTRY_SIZE)?)?;
        Some((
            u32::from_le_bytes(bytes[0..4].try_into().ok()?),
            u32::from_le_bytes(bytes[4..8].try_into().ok()?),
            u32::from_le_bytes(bytes[8..12].try_into().ok()?),
        ))
    }

    /// Look up the symbol containing `ip`.
    fn lookup(&self, ip: usize) -> Option<SymbolRef<'_>> {
        if self.count == 0 {
            return None;
        }
        let lo = (ip & 0xffff_ffff) as u32;
        // Binary search for the last entry whose address is <= `ip`.
        let mut low = 0usize;
        let mut high = self.count;
        while low < high {
            let mid = low + (high - low) / 2;
            let (addr_lo, ..) = self.entry(mid)?;
            if addr_lo <= lo {
                low = mid + 1;
            } else {
                high = mid;
            }
        }
        if low == 0 {
            return None;
        }
        let (addr_lo, size, name_off) = self.entry(low - 1)?;
        let start = self.addr_high | addr_lo as usize;
        let size = size as usize;
        let end = if size > 0 {
            start + size
        } else {
            // Size unknown: use the next symbol as the boundary.
            self.entry(low).map_or(usize::MAX, |(next_lo, ..)| {
                self.addr_high | next_lo as usize
            })
        };
        if ip < start || ip >= end {
            return None;
        }
        let name = self.name(name_off as usize)?;
        Some(SymbolRef {
            name,
            offset: ip - start,
            size,
        })
    }

    fn name(&self, offset: usize) -> Option<&'a [u8]> {
        let rest = self.names.get(offset..)?;
        let end = rest.iter().position(|&byte| byte == 0)?;
        Some(&rest[..end])
    }
}

/// Global symbol table, parsed once from the embedded blob.
static SYMTAB: Once<Option<KernelSymtab<'static>>> = Once::new();

/// Parse the embedded symbol table. Called once from `backtrace::init`.
pub(crate) fn init() {
    SYMTAB.call_once(|| KernelSymtab::parse(&KSYMTAB_BLOB));
}

/// Append ` name+0xoff/0xsize` for the given instruction pointer.
///
/// Outputs nothing when the symbol table is unavailable or the address is
/// not covered by any symbol, keeping the raw address line self-contained.
pub(crate) fn write_annotation(f: &mut fmt::Formatter<'_>, ip: usize) -> fmt::Result {
    let Some(Some(symtab)) = SYMTAB.get() else {
        return Ok(());
    };
    let Some(symbol) = symtab.lookup(ip) else {
        return Ok(());
    };
    let name = core::str::from_utf8(symbol.name).unwrap_or("<invalid>");
    write!(f, " {name}+{:#x}/{:#x}", symbol.offset, symbol.size)
}

#[cfg(unittest)]
mod tests_unittest {
    use alloc::vec::Vec;

    use unittest::def_test;

    use super::*;

    /// Build a blob: header + `entries` + names.
    fn blob(addr_high: u32, entries: &[(u32, u32, u32)], names: &[u8]) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&SYMTAB_MAGIC.to_le_bytes());
        bytes.extend_from_slice(&(entries.len() as u32).to_le_bytes());
        bytes.extend_from_slice(&addr_high.to_le_bytes());
        bytes.extend_from_slice(&(names.len() as u32).to_le_bytes());
        for (addr_lo, size, name_off) in entries {
            bytes.extend_from_slice(&addr_lo.to_le_bytes());
            bytes.extend_from_slice(&size.to_le_bytes());
            bytes.extend_from_slice(&name_off.to_le_bytes());
        }
        bytes.extend_from_slice(names);
        bytes
    }

    #[def_test]
    fn parse_rejects_bad_magic_and_truncated_blobs() {
        assert!(KernelSymtab::parse(&[]).is_none());
        assert!(KernelSymtab::parse(&[0u8; 8]).is_none());
        let mut bad = blob(0xffff_8000, &[], &[]);
        bad[0] = 0x00; // corrupt magic
        assert!(KernelSymtab::parse(&bad).is_none());
        // Truncated entry region.
        let full = blob(0xffff_8000, &[(0x1000, 8, 0)], b"foo\0");
        assert!(KernelSymtab::parse(&full[..full.len() - 1]).is_none());
    }

    #[def_test]
    fn lookup_handles_first_last_and_gaps() {
        let names = b"alpha\0beta\0gamma\0";
        let entries = [(0x1000, 0x10, 0), (0x2000, 0x10, 6), (0x3000, 0x10, 11)];
        let bytes = blob(0xffff_8000, &entries, names);
        let symtab = KernelSymtab::parse(&bytes).unwrap();
        let base = 0xffff_8000_0000_0000usize;

        // First symbol, offset inside.
        let symbol = symtab.lookup(base | 0x1005).unwrap();
        assert_eq!(symbol.name, b"alpha");
        assert_eq!(symbol.offset, 5);
        assert_eq!(symbol.size, 0x10);
        // Last symbol.
        assert_eq!(symtab.lookup(base | 0x300f).unwrap().name, b"gamma");
        // Gap between symbols: not covered.
        assert!(symtab.lookup(base | 0x1010).is_none());
        // Before the first symbol.
        assert!(symtab.lookup(base | 0x0fff).is_none());
        // Past the last symbol.
        assert!(symtab.lookup(base | 0x3010).is_none());
    }

    #[def_test]
    fn lookup_uses_next_symbol_as_boundary_when_size_is_zero() {
        let names = b"a\0b\0";
        let entries = [(0x1000, 0, 0), (0x2000, 0x10, 2)];
        let bytes = blob(0xffff_8000, &entries, names);
        let symtab = KernelSymtab::parse(&bytes).unwrap();
        let base = 0xffff_8000_0000_0000usize;

        // Size-0 entry extends to the next symbol.
        assert_eq!(symtab.lookup(base | 0x1fff).unwrap().name, b"a");
        // The next symbol's start belongs to that symbol, not the size-0 one.
        assert_eq!(symtab.lookup(base | 0x2000).unwrap().name, b"b");
    }
}
