[package]
name = "memspace"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true

[features]
default = []
copy = ["page_table/copy-from"]

[dependencies]
kalloc = { workspace = true }
kerrno = { workspace = true }
khal = { workspace = true }
kplat = { workspace = true }
ksync = { workspace = true }
kspin = { workspace = true }
lazyinit = { workspace = true }
log = { workspace = true }
memaddr = { workspace = true }
memset = { workspace = true }
page_table = { workspace = true }
unittest.workspace = true
kbuild_config = { workspace = true }
karch = { workspace = true }
kaddr_layout = { workspace = true }
